FROM node
ARG FOLDER=./front-end
# Set working directory
RUN mkdir app
WORKDIR /app
RUN echo $FOLDER

# Copy package.json and package-lock.json (if applicable)
COPY $FOLDER/package*.json ./

# Install dependencies
RUN npm install

# Copy source code into container

COPY $FOLDER .


# Expose the port used by the app
EXPOSE 3000

# Start the app
CMD ["npm","start"]
