FROM node
ARG FOLDER=./front-end
ARG PORT=3000

# Set working directory
RUN mkdir app
WORKDIR /app
RUN echo $FOLDER


# Copy package.json and package-lock.json (if applicable)
COPY $FOLDER/package*.json ./

# Install dependencies
RUN npm install

# Copy source code into container

COPY $FOLDER .
RUN npm run build


# Expose the port used by the app
EXPOSE $PORT

# Start the app
CMD ["npx","serve","dist"]
